### ISSUE TITLE
Fastify support?

### ISSUE THREAD

**Issue by patrickcurl** [xgenecloud/xgenecloud#19]
**Feature request is in**
[ ] CLI
[ ] Desktop App
[x] REST API Framework
[x] GraphQL API Framework

I was benchmarking using wrk -t 12 -c 100 -d 20 http://localhost:8080/api/v1/category which is just a  list of 20 categories from postgres. On a 16 core desktop w/ 64MB Ram, best I could get was 1357 reqs/sec. 

i was able to get more out of php/swoole, fastify, rust, go, any thoughts on ways the api's could be maximized for speed/load? I'm new to serverless, would that make this moot, since could potentially have 1 user hitting same api but across multiple serverless servers?

**Comment by o1lab** [comment]
Improvement to this can be done by keeping the express-session in redis instead of database (postgres). Also node is single threaded - so one of the core would be used at a time. Please use PM2 to use all cores.

Fastify support as of now - we've no plans. And it would not be fair to compare node with rust/golang. I 've never tried them but I imagine they can do better.

And looks like for 100 connections - [1537](https://medium.com/@onufrienkos/express-vs-fastify-performance-4dd5d73e08e2) reqs/sec is on par.

Please let us the results with PM2 for reference.

**Comment by o1lab** [comment]
>> I'm new to serverless, would that make this moot, since could potentially have 1 user hitting same api but across multiple serverless servers?

Our serverless use case is the idea of writing an express app where every API route is a serverless function. Mainly, this could avoid developer to write serverless specific code.

**Comment by patrickcurl** [comment]
Okay, yeah redis def. changes things.
Even using pm2 in cluster mode for some reason it was blocking and stuck at
1400'ish req/s
Changing to redis got me: 7839 req/s which is def more palatable.

I'm looking for a cross between high perf and easy/fast dev (tired of all
the manual boilerplate all the time),
which is why I'm benchmarking before building, this sits right in the sweet
spot.

**Comment by o1lab** [comment]
Thank you @patrickcurl for your finding. Really helpful.

We'd done benchmarking on pm2 a while ago. On a 6 core machine - it got twice as faster. However I cant remember the name. I guess there are some unnecessary logs in the output - removing them will also help.

If you have any numbers on rust/go that would be helpful too.
